SCENARIO_STORY_EXAMPLES = {'potato_chip_food': {'scenario': '[Food items bought in grocery stores cannot be closely examined for their quality before checking out]\nWhen person X buys a food item Z in a grocery store and something hidden is wrong with the food, then person X will not know about it before paying for it. For example, a carton of milk that has gone bad because of improper storage.',
  'entities': 'Person X = Mary\nObject Z = bag of sealed potato chips',
  'key_information': 'The bag of potato chips has a dead cockroach in it.',
  'story_sentence': 'Mary picks up the bag in the supermarket and walks to the cashier.',
  'question': 'What will Mary likely do next?',
  'correct_answer': 'pay for the chips',
  'incorrect_answer': 'report the dead cockroach',
  'sev1': 'The bag of potato chips has moldy chips in it.',
  'incorrect_answer_sev1': 'report the moldy chips',
  'sev3': 'The sealed bag of potato chips has several fried rats in it.',
  'incorrect_answer_sev3': 'report the fried rats'},
 'toe_hidden': {'scenario': '[Body features hidden under clothing cannot be observed]\nIf person Y has an issue with a part Z of their body which is generally hidden under their clothes or shoes, then person X will not know about it. For example, person Y has a scar on their stomach at school.',
  'entities': "Person X = John's classmate\nPerson Y = John\nObject Z = toe area of socks",
  'key_information': "In school, John's socks has some vulgarities printed near the toe area.",
  'story_sentence': "John's classmate walks to him during lunch.",
  'question': "What will John's classmate likely do?",
  'correct_answer': 'greet John',
  'incorrect_answer': 'be offended by the vulgarities',
  'sev1': "In school, John's socks has a hole near the toe area.",
  'incorrect_answer_sev1': 'tease John about his socks',
  'sev3': "In school, John's socks has a gang membership logo near the toe area.",
  'incorrect_answer_sev3': 'be concerned about the gang membership logo'},
 'house_buying': {'scenario': '[Hidden flaws in second-hand items bought cannot be observed before the purchase]\nWhen person Y has an item Z and something hidden is wrong with the item, then person X, a potential buyer of the item Z will not know about it, especially if person Y focuses on showcasing what is good about item Z. For example, a fridge that has problems like it occasionally emits a loud sound.',
  'entities': 'Person X = potential buyers\nPerson Y = John\nObject Z = beautiful villa',
  'key_information': "John's house is a beautiful villa but many wires are incorrectly connected.",
  'story_sentence': 'On a beautiful day, John showcases his beautiful villa to potential buyers.',
  'question': "What will John's potential buyers likely do during the viewing process?",
  'correct_answer': 'praise the beautiful villa as gorgeous',
  'incorrect_answer': 'express concerns about the incorrectly connected wires',
  'sev1': "John's house is a beautiful villa but with washer and dryer machines that are loud.",
  'incorrect_answer_sev1': 'express concerns about the washer and dryer',
  'sev3': "John's house is a beautiful villa but was used as a hideout for a serial killer.",
  'incorrect_answer_sev3': 'worry about the serial killer having been here'},
 'school_bag': {'scenario': '[What is inside (opaque) containers for personal belongings cannot be observed before opening the container]\nWhen person Y brings something in an opaque container Z for personal belongings, person X seeing container Z will not know what is inside. For example, person Y brings a new toy in his school bag.',
  'entities': "Person X = John's classmate\nPerson Y = John\nObject Z = school bag",
  'key_information': 'John brought a bag of candy in his school bag today.',
  'story_sentence': "John's classmate sees him waiting for the school bus to school.",
  'question': "What will John's classmate likely do?",
  'correct_answer': 'approach John to greet him',
  'incorrect_answer': 'wonder if John would share the candy',
  'sev1': 'John brought a new, limited edition toy in his school bag today.',
  'incorrect_answer_sev1': 'ask John to show him the toy',
  'sev3': 'John brought a bomb in his school bag today.',
  'incorrect_answer_sev3': 'stay away from John and call the police'},
 'KFC_bag': {'scenario': '[What is inside labeled (opaque) containers cannot be observed before opening the container]\nWhen person Y brings something in a (opaque) container Z labeled with a popular brand, person X seeing the container will infer it is something from the brand and not know what is inside (such as if it contains something completely different). For example, person Y put yogurt in a KFC paper bag.',
  'entities': "Person X = Mary's classmate\nPerson Y = Mary\nObject Z = KFC paper bag",
  'key_information': 'Mary sealed a yogurt in a KFC paper bag and brought the bag to school.',
  'story_sentence': "Mary's classmate sees her walking to lunch with the sealed bag.",
  'question': "What will Mary's classmate likely do?",
  'correct_answer': 'offer to bring Mary a fork',
  'incorrect_answer': 'offer to bring Mary a spoon',
  'sev1': 'Mary sealed a container of Michelin star Chinese congee in a KFC paper bag and brought the bag to school.',
  'incorrect_answer_sev1': 'offer to bring Mary a spoon',
  'sev3': 'Mary sealed a container of plain water in a KFC paper bag and brought the bag to school.',
  'incorrect_answer_sev3': 'ask Mary why she brings a container of plain water'},
 'organic_fruits': {'scenario': '[Subtle properties of products cannot be closely examined or verified]\nWhen a seller labels product Z with a subtle property that helps them sell product Z for a higher price, but product Z does not have that property, a potential buyer X will not have enough information to know that. For example, shop owner puts fancy "organic" labels on normal fruits and sells them at a much higher price.',
  'entities': 'Person X = potential buyers\nObject Z = fruits',
  'key_information': 'The shop owner puts fancy "organic" labels strategically to cover spots on slightly old fruits and sells them at a much higher price.',
  'story_sentence': 'The shop owner recommends the labeled fruits to customers.',
  'question': "How will the shop owner's potential buyers likely react?",
  'correct_answer': 'buy the labeled fruits at higher price',
  'incorrect_answer': 'complain about slightly old fruits being sold at a higher price',
  'sev1': 'The shop owner puts fancy "organic" labels on normal fruits and sells them with a much higher price.',
  'incorrect_answer_sev1': 'complain about normal fruits being sold at a higher price',
  'sev3': 'The shop owner puts fancy "organic" labels strategically to cover bitten spots on rat-bitten fruits and sells them with a much higher price.',
  'incorrect_answer_sev3': 'complain about rat-bitten fruits being sold at a higher price'},
 'high_risk_operation': {'scenario': '[Efficacy of healthcare products cannot be closely examined or verified before purchase]\nWhen a provider know that healthcare product Z has important limitations that should deter a consumer X from using it, they can still try to sell Z to consumer X in interest of earning money from it, by focusing on promoting the benefits and not disclosing the limitations. For example, a new drug has several suspected side effects that were not reported.',
  'entities': 'Person X = patient\nObject Z = operation',
  'key_information': "The doctor knows that the operation on this patient has a low success rate due to the patient's pre-existing conditions but still eagerly recommends it to the patient out of self-interest to earn money from it.",
  'story_sentence': 'The doctor recommends the operation procedure to the patient, promoting its health benefits.',
  'question': 'What will the patient likely do?',
  'correct_answer': 'have the operation',
  'incorrect_answer': 'worry about the low success rate',
  'sev1': "The doctor knows that the operation on this patient will only improve their conditions minimally due to the patient's pre-existing conditions, but still eagerly recommends it to the patient out of self-interest to earn money from it.",
  'incorrect_answer_sev1': 'worry that the improvement in conditions will be minimal',
  'sev3': "The doctor knows that the operation on this patient will kill them due to the patient's pre-existing conditions, but still eagerly recommends it to the patient out of self-interest to earn money from it.",
  'incorrect_answer_sev3': 'refuse the operation to stay alive'},
 'questionable_chef': {'scenario': '[Questionable behind-the-scenes practices in the service industry are not observed by customers]\nWhen person/business Z in the service industry has questionable behind-the-scenes practice, the business can still try to promote their service to consumer X by focusing on promoting the attractive side. For example, the chef of a restaurant is reusing the wok without cleaning it for several days.',
  'entities': 'Person X = potential consumers\nPerson Z = chef of restaurant',
  'key_information': 'The chef of this restaurant reuses the wok without cleaning for several days in his cooking.',
  'story_sentence': 'The restaurant manager actively promotes the dishes to the customers, focusing on how tasty they are.',
  'question': 'What will potential consumers likely do?',
  'correct_answer': 'eagerly try out some dishes',
  'incorrect_answer': "express disgust about the chef's hygiene practices",
  'sev1': 'The chef of this restaurant reuses the wok without cleaning for a day in his cooking.',
  'incorrect_answer_sev1': "be slightly concerned about the chef's reuse of the wok",
  'sev3': 'The chef of this restaurant kills stray dogs and uses their meat for the beef items in his cooking.',
  'incorrect_answer_sev3': "alert authorities about the chef's meat sources"},
 'utility_bill': {'scenario': '[Details in locked devices or accounts cannot be observed by others]\nWhen person Y has a locked device or account Z, their status or activity in Z are not observed by person X. For example, person X does not have access to person Y’s utility bill account so they would not know when person Y forgot to pay for his utility bill.',
  'entities': 'Person X = relative\nPerson Y = John\nObject Z = utility bill account',
  'key_information': 'John forgot to pay for his utility bill for two months, and a warning on this was sent to his utility bill account.',
  'story_sentence': "John's relative visits John.",
  'question': "What will John's relative likely do?",
  'correct_answer': 'ask John how he is doing',
  'incorrect_answer': 'ask John if he is having any trouble paying the utility bill',
  'sev1': 'John won a lucky draw as part of the activities organized by the utility bill company, and a message on this was sent to his utility bill account.',
  'incorrect_answer_sev1': 'congratulate John on winning the lucky draw',
  'sev3': "John's utility bill got hacked into and the recent bill amount reflected is over 10 thousand dollars.",
  'incorrect_answer_sev3': 'help John alert authorities about the hacking'},
 'exam_cheating': {'scenario': '[Unethical actions not observed are not known]\nWhen person Y performs unethical action Z, and person X is not in the right place or time to observe Y performing Z, person X would not know about Z. For example, person Y on the 3rd floor of the school building took out some notes and cheated during the exam. Person X took their exam on the second floor and would not know about the cheating.',
  'entities': 'Person X = John\nPerson Y = schoolmate\nAction Z = cheated during the exam',
  'key_information': "John's schoolmate on the 3rd floor of the school building took out some notes and cheated during the exam.",
  'story_sentence': 'John, a righteous student, took his exam on the second floor and finished his exam.',
  'question': 'What will John likely do after the exam?',
  'correct_answer': 'go home',
  'incorrect_answer': 'report cheating',
  'sev1': "John's schoolmate on the 3rd floor of the school building took out some notes during an open book exam.",
  'incorrect_answer_sev1': 'report cheating',
  'sev3': "John's schoolmate on the 3rd floor of the school building coerced the top student of that class to give him answers during the exam.",
  'incorrect_answer_sev3': 'report cheating'}}

SCENARIO_NAMES_TO_STORY = {'food_item_in_grocery_store': 'potato_chip_food',
 'hidden_body_part_feature': 'toe_hidden',
 'seller_info_in_second_hand_market': 'house_buying',
 'inside_containers_for_personal_belongings': 'school_bag',
 'inside_reuse_labeled_containers': 'KFC_bag',
 'true_property_pretentious_labels': 'organic_fruits',
 'provider_info_healthcare': 'high_risk_operation',
 'behind_the_scene_service_industry': 'questionable_chef',
 'locked_devices_accounts': 'utility_bill',
 'unobserved_unethical_actions': 'exam_cheating'}


# For second round of generation to increase diversity in data
SCENARIO_STORY_EXAMPLES_2 = {'gen23': {'scenario_name': 'food_item_in_grocery_store',
  'entities': 'Person X = Emily\nObject Z = a jar of peanut butter',
  'key_information': 'The jar of peanut butter contains a highly toxic pesticide residue.',
  'story_sentence': 'Emily places the jar in her shopping cart and proceeds to the checkout line.',
  'question': 'What will Emily likely do next?',
  'correct_answer': 'pay for the peanut butter',
  'incorrect_answer': 'report the contaminated peanut butter to the store manager',
  'sev1': 'The jar of peanut butter is quite empty, appearing full but is actually half-empty.',
  'incorrect_answer_sev1': 'ask for a discount due to the reduced quantity',
  'sev3': 'The jar of peanut butter is part of a batch that has been recalled due to a fatal allergen contamination not listed on the label.',
  'incorrect_answer_sev3': 'inform the store manager about the recall and refuse to buy it'},
 'gen244': {'scenario_name': 'provider_info_healthcare',
  'entities': 'Person X = Emily (a patient)\nObject Z = Anti-aging cream',
  'key_information': "The dermatologist knows that the anti-aging cream contains an ingredient that commonly causes severe allergic reactions in people with Emily's skin type, but still eagerly recommends it to her out of self-interest to earn a commission from its sale.",
  'story_sentence': 'The dermatologist recommends the anti-aging cream to Emily, touting its effectiveness in reducing wrinkles and fine lines.',
  'question': 'What will Emily likely do?',
  'correct_answer': 'purchase the anti-aging cream',
  'incorrect_answer': 'avoid the cream due to the risk of a severe allergic reaction',
  'sev1': "The dermatologist knows that the anti-aging cream is only minimally effective for people with Emily's skin type, but still eagerly recommends it to her out of self-interest to earn a commission from its sale.",
  'incorrect_answer_sev1': 'question whether the cream is worth purchasing given its minimal effectiveness',
  'sev3': "The dermatologist knows that the anti-aging cream contains an ingredient that has been linked to causing skin cancer in people with Emily's skin type, but still eagerly recommends it to her out of self-interest to earn a commission from its sale.",
  'incorrect_answer_sev3': 'refuse to purchase the cream due to the cancer risk'},
 'gen218': {'scenario_name': 'true_property_pretentious_labels',
  'entities': 'Person X = Music aficionado\nObject Z = Vinyl record',
  'key_information': "The record store owner puts a rare, limited edition sticker on a regular vinyl record and sells it at a collector's price.",
  'story_sentence': 'John, a music aficionado, eagerly browses through the crates of vinyl records at his local record store.',
  'question': 'What will John likely do upon finding the vinyl record?',
  'correct_answer': 'be interested in purchasing the vinyl record at the price offered',
  'incorrect_answer': 'confront the store owner about falsely labeling a regular record as a rare edition',
  'sev1': 'The record store owner puts a sticker indicating a slightly better sound quality on a regular vinyl record and sells it at a higher price.',
  'incorrect_answer_sev1': 'question the store owner about the validity of the claimed sound quality improvement',
  'sev3': "The record store owner puts a rare, limited edition sticker on a counterfeit vinyl record with significant audio flaws and sells it at a high collector's price.",
  'incorrect_answer_sev3': 'develop negative impression of the store owner for selling counterfeit records with major defects as rare editions'},
 'gen332': {'scenario_name': 'behind_the_scene_service_industry',
  'entities': 'Person X = Richard, a car owner\nPerson Z = Auto repair shop',
  'key_information': 'The auto repair shop uses cheap, substandard parts when doing repairs, despite charging for high-quality parts.',
  'story_sentence': 'Richard drops off his car at the repair shop for a brake job, and the mechanic assures him they will do a thorough, top-notch job.',
  'question': 'What will Richard likely do after the repair is completed?',
  'correct_answer': 'Pick up his car and drive away satisfied, believing he got a quality brake repair',
  'incorrect_answer': 'Confront the shop about the substandard parts and demand they redo the job properly or refund his money',
  'sev1': 'The auto repair shop uses average-quality aftermarket parts when doing repairs, despite charging for high-quality OEM parts.',
  'incorrect_answer_sev1': 'Express disappointment to the shop about not getting the OEM parts he paid for and ask for a partial refund',
  'sev3': 'The auto repair shop intentionally damages other components of the car during repairs in order to force the owner to pay for additional fixes.',
  'incorrect_answer_sev3': 'Refuse to pay, take his car to another shop to undo the sabotage'},
 'gen168': {'scenario_name': 'inside_reuse_labeled_containers',
  'entities': "Person X = Lisa's friend\nPerson Y = Lisa\nObject Z = Cookie tin",
  'key_information': 'Lisa stored her collection of rare coins in a Danish butter cookie tin and placed it on the kitchen counter.',
  'story_sentence': "Lisa's friend comes over and notices the tin sitting on the counter.",
  'question': "What will Lisa's friend likely do?",
  'correct_answer': 'ask Lisa if she can have some of the cookies',
  'incorrect_answer': 'ask Lisa about her coin collection in the tin',
  'sev1': 'Lisa stored her sewing supplies in a Danish butter cookie tin and placed it on the kitchen counter.',
  'incorrect_answer_sev1': 'ask Lisa if she can borrow some thread from the tin',
  'sev3': "Lisa stored her deceased grandmother's ashes in a Danish butter cookie tin and placed it on the kitchen counter.",
  'incorrect_answer_sev3': "express condolences and ask Lisa about her grandmother's passing"},
 'gen368': {'scenario_name': 'unobserved_unethical_actions',
  'entities': 'Person X = Alex\nPerson Y = business partner\nAction Z = plans with a competitor',
  'key_information': "Alex's business partner had a clandestine meeting with their biggest competitor to secretly negotiate a lucrative deal that would undercut their own company.",
  'story_sentence': 'Alex, meanwhile, was focused on diligently working on a new marketing strategy to boost sales and outperform the competition.',
  'question': 'What will Alex likely do after finishing the marketing strategy?',
  'correct_answer': 'present the strategy to the business partner',
  'incorrect_answer': "investigate the business partner's actions toward the secret deal",
  'sev1': "Alex's business partner had a chat with an old friend who happens to work for a competitor, discussing plans to work collaboratively rather than compete against each other.",
  'incorrect_answer_sev1': 'discuss the meeting with the business partner to learn more about their collaborative plans',
  'sev3': "Alex's business partner secretly sold off all their company shares and intellectual property rights to their biggest competitor, effectively handing over control of the company without Alex's knowledge.",
  'incorrect_answer_sev3': "take immediate legal action against the business partner and the competitor to protect the company's assets and future"},
 'gen128': {'scenario_name': 'inside_containers_for_personal_belongings',
  'entities': "Person X = Ethan's roommate\nPerson Y = Ethan\nObject Z = non-transparent gym bag",
  'key_information': "Ethan's gym bag contains a large sum of stolen cash.",
  'story_sentence': "Ethan's roommate notices him hurriedly heading out the door with his gym bag.",
  'question': "What will Ethan's roommate likely do?",
  'correct_answer': 'assume Ethan is late for his workout and going to the gym',
  'incorrect_answer': 'assume Ethan is hurrying out to carry out some illegal activities with the stolen money',
  'sev1': "Ethan's gym bag contains a secret love letter he wrote to his crush.",
  'incorrect_answer_sev1': 'assume Ethan is rushing to pass the love letter to his crush',
  'sev3': "Ethan's gym bag contains a loaded gun and a detailed plan for a mass shooting.",
  'incorrect_answer_sev3': "be afraid of Ethan's dangerous intentions of carrying out mass shooting and plan to move out to distance himself"},
 'gen108': {'scenario_name': 'seller_info_in_second_hand_market',
  'entities': 'Person X = potential buyers\nPerson Y = David\nObject Z = luxury yacht',
  'key_information': "David's luxury yacht has a hidden structural defect that compromises its seaworthiness.",
  'story_sentence': 'On a sunny afternoon, David enthusiastically presents his luxurious yacht to potential buyers, highlighting its state-of-the-art features and sleek design.',
  'question': "What will David's potential buyers likely do after the yacht presentation?",
  'correct_answer': 'have strong interest in the impressive luxury yacht, viewing it as perfect',
  'incorrect_answer': "voice serious reservations about the yacht's structural integrity and seaworthiness",
  'sev1': "David's luxury yacht has an electrical issue causing the interior lights to not work when there is no solar energy.",
  'incorrect_answer_sev1': 'inquire about the electrical system and the situation of the lights',
  'sev3': "David's luxury yacht was previously owned by a notorious drug cartel and has hidden compartments filled with illegal substances.",
  'incorrect_answer_sev3': "immediately contact the authorities to report the yacht's criminal history and contraband"},
 'gen58': {'scenario_name': 'hidden_body_part_feature',
  'entities': "Person X = Lisa's boyfriend\nPerson Y = Lisa\nObject Z = pendant",
  'key_information': "Lisa's pendant contains a tiny photo of her ex-boyfriend.",
  'story_sentence': "Lisa's boyfriend surprises her with a romantic candlelit dinner at home.",
  'question': "What will Lisa's boyfriend likely do?",
  'correct_answer': 'compliment Lisa on her pendant',
  'incorrect_answer': 'confront Lisa about the photo of her ex',
  'sev1': "Lisa's pendant was a gift from a male coworker who is pursuing Lisa.",
  'incorrect_answer_sev1': 'feel jealous about the gift-giver',
  'sev3': "Lisa's pendant contains a tiny vial of poison.",
  'incorrect_answer_sev3': 'be horrified about the poison'},
 'gen316': {'scenario_name': 'locked_devices_accounts',
  'entities': "Person X = Tom (John's landlord)\nPerson Y = John\nObject Z = password-protected computer files",
  'key_information': "John's computer files contain evidence that he has been embezzling money from his company.",
  'story_sentence': "Tom visits John's apartment to collect the monthly rent.",
  'question': 'What will Tom likely do after collecting the rent from John?',
  'correct_answer': "leave John's apartment and go about his day as usual",
  'incorrect_answer': "leave John's apartment thinking about John's embezzlement and whether to report him to the authorities",
  'sev1': 'John\'s computer files reveal that he is a super popular writer with the pen name of "J" and has been secretly working on a novel in his spare time.',
  'incorrect_answer_sev1': "be inspired by John's side career as a writer",
  'sev3': "John's computer files contain detailed plans for a terrorist attack targeting a major city.",
  'incorrect_answer_sev3': "leave John's apartment feeling terrified of the terrorist plot, and make plans to stop renting to John to avoid potential trouble "}}

SCENARIO_NAMES_TO_STORY_2 = {'food_item_in_grocery_store': 'gen23',
 'provider_info_healthcare': 'gen244',
 'true_property_pretentious_labels': 'gen218',
 'behind_the_scene_service_industry': 'gen332',
 'inside_reuse_labeled_containers': 'gen168',
 'unobserved_unethical_actions': 'gen368',
 'inside_containers_for_personal_belongings': 'gen128',
 'seller_info_in_second_hand_market': 'gen108',
 'hidden_body_part_feature': 'gen58',
 'locked_devices_accounts': 'gen316'}


